name: My first workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet user
        run: |
          echo "Hello ${{vars.WHO_TO_GREET}} from ${{ github.actor }}."
          echo "My secret is ${{ secrets.MY_SECRET }}."
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - run: tree
        shell: bash
    
